bookstore/books/urls.py
from django.conf.urls import  url
from books import views

urlpatterns = [
    url(r'^index/$', views.index, name='book_index'),
    url(r'^(?P<books_id>\d+)/$', views.detail, name='book_detail'),  # 配置详情页路由
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name = 'list'), # 列表页


]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import users

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^book/', include('books.urls', namespace='book')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
    url(r'^search/', include('haystack.urls')),
]

bookstore/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'), #添加购物车数据
    url(r'^count/$', views.cart_count, name='count'), # 获取用户购物车中的商品数量
    url(r'^show/$', views.cart_show, name='show'), # 显示用户的购物车页面
    url(r'^del/$', views.cart_del, name='delete'), # 购物车商品记录删除
    url(r'^update/$', views.cart_update, name='update'), # 更新购物车中的数据
    ]

bookstore/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_check/$', views.login_check, name='login_check'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^info_center/$', views.user, name='info_center'),
    url(r'^order/$', views.order, name='order'),
    url(r'^address/$', views.address, name='address'),

]

bookstore/users/models.py
from django.db import models
from db.base_model import BaseModel
from public.get_hash import get_hash


# TODO Create your models here.
# TODO 实现添加和查找账户信息的功能
# TODO 自定义管理器
class PassportManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_delete=False)

    # TODO 添加一个账户信息
    def add_one_passport(self, username, password, email):
        passport = self.create(username=username, password=get_hash(password), email=email)
        return passport

    # TODO 根据账户信息查找密码
    def get_one_passport(self, username, password):
        try:
            passport = self.get(username=username, password=get_hash(password))
        except self.model.DoesNotExist:
            # TODO 账户不存在
            passport = None
        return passport


# 实现地址模型的管理器
class AddressManager(models.Manager):

    def get_default_address(self, passport_id):
        """查询指定用户的默认收货地址"""
        try:
            addr = self.get(passport_id=passport_id, is_default=True)
        except self.model.DoesNotExist:
            # 没有默认收货地址
            addr = None
        return addr

    def add_one_address(self, passport_id, recipient_name, recipient_addr, zip_code, recipient_phone):
        # 添加收货地址
        # 判断用户是否有默认收货地址
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            # 存在默认地址
            is_default = False
        else:
            # 不存在默认地址
            is_default = True

        # 添加一个地址
        addr = self.create(passport_id=passport_id,
            recipient_name=recipient_name,
            recipient_addr=recipient_addr,
            zip_code=zip_code,
            recipient_phone=recipient_phone,
            is_default=is_default)


        return addr


class Passport(BaseModel):
    # 用户模型类
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')
    # TODO 使用自定义的管理器
    objects = PassportManger()

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        db_table = 's_user_account'

    def __str__(self):
        return self.username


# todo 创建用户地址的表
class Address(BaseModel):
    """地址模型类"""
    recipient_name = models.CharField(max_length=100, verbose_name='收件人')
    recipient_addr = models.CharField(max_length=300, verbose_name='收件人地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')
    passport = models.ForeignKey('Passport', verbose_name='账户')

    objects = AddressManager()

    class Meta:
        db_table = 's_user_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

    def  __str__(self):
        return self.recipient_name

bookstore/users/views.py
from django.shortcuts import render, redirect
import re
from .models import Passport, Address
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from utils.decorators import login_required
from order.models import OrderInfo, OrderBooks
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from django.conf import settings
from django.core.mail import send_mail
from users.tasks import send_active_email
# Create your views here.


def register(request):

    return render(request, 'users/register.html')


def register_handle(request):
    """对用户的注册信息进行处理"""
    # TODO 接收数据
    username = request.POST.get('user_name', '')
    password = request.POST.get('pwd', '')
    email = request.POST.get('email', '')
    # 不能用中文注册
    if not re.match(r'^[a-zA-Z0-9_-]{4,16}$', username):
        return render(request, 'users/register.html', {'errmsg': '用户名只能包含大小写字母数下划线以及-号!'})
    # TODO 进行数据校验
    if not all([username, password, email]):
        # 如果数据有空
        return render(request, 'users/register.html', {'errmsg': '输入的信息不能为空,请核对后再重新输入!'})
    # TODO 验证邮箱地址
    if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
        # 邮箱不合法
        return render(request, 'users/register.html', {'errmsg': '邮箱格式输入有误,请重新输入!'})
    # TODO 验证通过　将注册信息添加到数据库

    p = Passport.objects.filter(username=username)

    if p:
        return render(request, 'users/register.html', {'errmsg':'用户名已经存在'})
    passport = Passport.objects.add_one_passport(username=username, password=password, email=email)
    # 记住登录状态
    request.session['islogin'] = True
    request.session['username'] = username
    request.session['passport_id'] = passport.id
    # 生成激活的token itsdeangerous
    serializer = Serializer(settings.SECRET_KEY, 3600)
    token = serializer.dumps({'confirm':passport.id})
    token = token.decode('utf8')
    # 给用户的邮箱发送激活邮件
    # send_mail('书城用户激活','', settings.EMAIL_FROM, [email],html_message='<a href="http://192.168.28.66:8000/user/active/%s/">http://192.168.28.66:8000/user/active/</a>' % token)
    send_active_email.delay(token, username, email)
    return redirect(reverse('book:book_index'))



# todo 显示登录界面
def login(request):
    """显示登录界面"""
    username = request.COOKIES.get('username', '')
    checked = ''
    context = {
        'username': username,
        'checked': checked,
    }
    return render(request, 'users/login.html', context)


# todo 登录数据的校验功能,还有记住用户名的功能
def login_check(request):
    # 1.获取数据
    username = request.POST['username']
    password = request.POST['password']
    remember = request.POST['remember']
    # 2.数据校验
    if not all([username, password, remember]):
        # 有数据为空
        return JsonResponse({'res': 2})
    # 3.进行处理:根据用户名和密码查找用户信息
    passport = Passport.objects.get_one_passport(username=username, password=password)
    if passport:
        # 用户名密码正确
        # 获取session中的url_path
        # if request.session.has_key('url_path')
        #   next_url = request.session.get('url_path')
        # else:
        #   next_url = reverse('book:index')
        next_url = request.session.get('url_path', reverse('book:book_index'))
        jres = JsonResponse({'res': 1, 'next_url': next_url})

        # 判断是否需要记住用户名
        if remember == 'true':
            # 记住用户名
            jres.set_cookie('username', username, max_age=7 * 24 * 3600)
        else:
            # 不记住用户名
            jres.delete_cookie('username')
        # 记住用户的登录状态
        request.session['islogin'] = True
        request.session['username'] = username
        request.session['passport_id'] = passport.id
        return jres
    else:
        # 用户名或密码错误
        return JsonResponse({'res': 0})


def logout(request):
    """用户退出登录"""
    # 清空用户的session信息
    request.session.flush()
    # 跳转到首页
    return redirect(reverse('book:book_index'))

@login_required
def user(request):
    """用户中心-信息页"""
    passport_id = request.session.get('passport_id')
    # 获取用户的基本信息
    addr = Address.objects.get_default_address(passport_id=passport_id)


    books_li = []

    context = {
        'addr':addr,
        'page':'user',
        'books_li': books_li,
    }

    return render(request, 'users/user_center_info.html', context)



@login_required
def order(request):
    # 用户中心订单页
    # 查询用户的订单信息
    passport_id = request.session.get('passport_id')

    # 获取订单信息
    order_li = OrderInfo.objects.filter(passport_id=passport_id)


    # 便利获取订单的商品信息
    # order->OrderInfo 实例对象
    for order in order_li:
        # 根据订单的ID查询订单商品信息
        order_id = order.order_id
        order_books_li = OrderBooks.objects.filter(order_id=order_id)


        # 计算商品的小计
        # order_books->OrderBooks实例对象
        for order_books in order_books_li:
            count = order_books.count
            price = order_books.price
            amount = count * price
            # 保存订单中每一个商品的小计
            order_books.amount = amount

        # 给order对象动态增加一个属性order_books_li,保存订单中商品的信息
        order.order_books_li = order_books_li

    context = {
        'order_li':order_li,
        'page':'order'
    }

    return render(request, 'users/user_center_order.html', context)



@login_required
def address(request):
    # 用户中心地址页
    # 获取登录用户的id
    passport_id = request.session.get('passport_id')

    if request.method == 'GET':
        # 显示地址页面
        # 查询用户的默认地址
        addr = Address.objects.get_default_address(passport_id=passport_id)
        return render(request, 'users/user_center_site.html', {'addr':addr, 'page':'address'})
    else:
        # 添加收货地址
        # 1. 接受数据
        recipient_name = request.POST.get('username')
        recipient_addr = request.POST.get('addr')
        recipient_phone = request.POST.get('phone')
        zip_code = request.POST.get('zip_code')

        # 2. 进行校验
        if not all ([recipient_addr, recipient_name, recipient_phone, zip_code]):
            return render(request, 'users/user_center_site.html', {'errmsg':'信息不能为空'})

        # 3.添加收货地址
        Address.objects.add_one_address(
            passport_id=passport_id,
            recipient_name=recipient_name,
            recipient_phone=recipient_phone,
            recipient_addr=recipient_addr,
            zip_code=zip_code,
        )

        # 4.返回应答
        return redirect(reverse('user:address'))

bookstore/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-登录{% endblock title %}

{% block topfiles %}
{% block cart_count %}{% endblock cart_count %}
<script>
    $(function () {
        $('#btnLogin').click(function () {
            // 获取用户名和密码
            username = $('#username').val();
            password = $('#pwd').val();
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            remember = $('input[name="remember"]').prop('checked');
            // 发起ajax请求
            params = {
                'username': username, 'password': password,
                'csrfmiddlewaretoken': csrf, 'remember': remember
            };

            $.post('/user/login_check/', params, function (data) {
                // 用户名密码错误 {'res': 0}
                // 登录成功 {'res': 1}
                if (!data.res) {
                    $('#username').next().html('用户名或密码错误').show()
                }
                else {
                    // 跳转页面
                    location.href = data.next_url // /user/
                }
            })
        })
    })
</script>
{% endblock topfiles %}
{% block header_con %}
{% endblock header_con %}
{% block search_bar %}
<div class="search_bar clearfix">
        <a href="{% url 'book:book_index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
</div>
{% endblock search_bar %}

{% block body %}
<body>
<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">学计算机 · 来尚硅谷</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'user:register' %}">立即注册</a>
            </div>
            <div class="form_input">
                {% comment %}<form>
						<input type="text" name="username" class="name_input" placeholder="请输入用户名", value="{{username}}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>{% endcomment %}
                {% csrf_token %}
                <input type="text" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                <div class="user_error">输入错误</div>
                <input type="password" id="pwd" class="pass_input" placeholder="请输入密码">
                <div class="pwd_error">输入错误</div>
                <div class="more_input clearfix">
                    <input type="checkbox" name="remember" {{ checked }}>
                    <label>记住用户名</label>
                    <a href="#">忘记密码</a>
                </div>
                <input type="button" id="btnLogin" value="登录" class="input_submit">
                <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

bookstore/templates/users/register.html
{% load staticfiles %}
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>尚硅谷书城-注册</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/register.js"></script>
    {% block cart_count %}{% endblock cart_count %}
</head>
<body>
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
        <div class="reg_slogan">学计算机 · 来尚硅谷</div>
        <div class="reg_banner"></div>
    </div>

    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>用户注册</h1>
            <a href="{% url 'user:login' %}">登录</a>
        </div>
        <div class="reg_form clearfix">
            <form method="post" action="{% url 'user:register_handle' %}">
                {% csrf_token %}
                <ul>
                    <li>
                        <label>用户名:</label>
                        <input type="text" name="user_name" id="user_name">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>密码:</label>
                        <input type="password" name="pwd" id="pwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>确认密码:</label>
                        <input type="password" name="cpwd" id="cpwd">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li>
                        <label>邮箱:</label>
                        <input type="text" name="email" id="email">
                        <span class="error_tip">提示信息</span>
                    </li>
                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>同意”尚硅谷书城用户使用协议“</label>
                        <span class="error_tip2">提示信息</span>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="注 册" name="submit">
                    </li>
                    <li> {{ errmsg }} </li>
                </ul>
            </form>


        </div>
    </div>

</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>

bookstore/templates/users/user_center_info.html
{% extends 'base.html' %}
<head>
{% block title %}用户信息中心{% endblock title %}
</head>

<body>
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info_center' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.session.username }}</li>
							{% if addr %}
								<li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
								<li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
							{% else %}
								<li><span>联系方式:</span>无</li>
								<li><span>联系方式:</span>无</li>
							{% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="book_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/book/book003.jpg"></a>
					<h4><a href="detail.html">Python Cookbook</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book004.jpg"></a>
					<h4><a href="#">Python高性能编程</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book005.jpg"></a>
					<h4><a href="#">Javascript高级程序设计</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book006.jpg"></a>
					<h4><a href="#">Javascript权威指南</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/book/book007.jpg"></a>
					<h4><a href="#">Javascript语言精粹</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">/册</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>
{% endblock body %}
</body>
</html>

bookstore/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load filters %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:info_center' %}">· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            {% csrf_token %}
            <h3 class="common_title2">全部订单</h3>
            {# OrderInfo #}
            {% for order in order_li %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress">{{ order.status }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {# 遍历出来的order_goods是一个OrderGoods对象 #}
                            {% for order_books in order.order_books_li %}
                                <ul class="order_book_list clearfix">
                                    <li class="col01"><img src="{% static order_books.books.image %}"></li>
                                    <li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em>
                                    </li>
                                    <li class="col03">{{ order_books.count }}</li>
                                    <li class="col04">{{ order_books.amount }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_price }}元</td>
                        <td width="15%">{{ order.status|order_status }}</td>
                        <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}"
                                           order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}

            <div class="pagenation">
                <a href="#">上一页</a>
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#">下一页></a>
            </div>
        </div>
    </div>
{% endblock body %}
{% block bottomfiles %}
    <script>
        $(function () {
            $('.oper_btn').click(function () {
                // 获取订单id和订单的状态
                order_id = $(this).attr('order_id')
                order_status = $(this).attr('order_status')
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                params = {'order_id': order_id, 'csrfmiddlewaretoken': csrf}
                if (order_status == 1) {
                    $.post('/order/pay/', params, function (data) {
                        if (data.res == 3) {
                            // 把用户引导支付页面
                            window.open(data.pay_url)
                            // 查询用户的支付结果
                            $.post('/order/check_pay/', params, function (data) {
                                if (data.res == 3) {
                                    alert('支付成功')
                                    // 重新刷新页面
                                    location.reload()
                                }
                                else {
                                    alert(data.errmsg)
                                }
                            })
                        }
                        else {
                            alert(data.errmsg)
                        }
                    })
                }
            })
        })
    </script>
{% endblock bottomfiles %}

bookstore/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-地址编辑{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info_center' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						    <dd>{{ addr.recipient_addr }} ({{ addr.recipient_name }} 收) {{ addr.recipient_phone }}</dd>
                        {% else %}
                            <dd>无</dd>
                        {% endif %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body %}