bookstore/books/urls.py
from django.conf.urls import  url
from books import views

urlpatterns = [
    url(r'^index/$', views.index, name='book_index'),
    url(r'^(?P<books_id>\d+)/$', views.detail, name='book_detail'),  # 配置详情页路由
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name = 'list'), # 列表页


]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import users

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^book/', include('books.urls', namespace='book')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
    url(r'^search/', include('haystack.urls')),
]

bookstore/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'), #添加购物车数据
    url(r'^count/$', views.cart_count, name='count'), # 获取用户购物车中的商品数量
    url(r'^show/$', views.cart_show, name='show'), # 显示用户的购物车页面
    url(r'^del/$', views.cart_del, name='delete'), # 购物车商品记录删除
    url(r'^update/$', views.cart_update, name='update'), # 更新购物车中的数据
    ]

bookstore/books/models.py
from db.base_model import BaseModel
from tinymce.models import HTMLField
from books.enums import *
from django.db import models


class BooksManager(models.Manager):
    """商品模型管理器"""
    # sort='new'        按照创建时间进行排序
    # sort='hot'        按照商品销量进行排序
    # sort='price'      按照商品的价格进行排序
    # sort=''           按照默认顺序排序
    def get_books_by_type(self, type_id, limit=None, sort='default'):
        """根据商品类型ｉｄ查询商品的信息"""
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales',)
        elif sort == 'price':
            order_by = ('price',)
        else:
            order_by = ('-pk', ) # 按照primary key降序排列

        # TODO　查询数据
        books_li = self.filter(type_id=type_id).order_by(*order_by)

        # 查询结果集的限制
        if limit:
            books_li = books_li[:limit]
        return  books_li

    def get_books_by_id(self, books_id):
        """根据商品的信息"""
        try:
            books = self.get(id=books_id)
        except self.model.DoesNotExist:
            # 不存在商品信息
            books = None
        return books

class Books(BaseModel):
    # TODO 商品的模型类
    books_type_choices = ((k, v) for k, v in BOOKS_TYPE.items())
    status_choices = ((k, v) for k, v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=100, verbose_name='商品名称')
    desc = models.CharField(max_length=200, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=100, verbose_name='商品库存')
    sales = models.IntegerField(default=100, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')


# for i in range(100):
#     book = Books()
#     book.name='python大法好'+str(i)
#     book.desc = 'python大法好,好啊真是好'
#     book.price = 100+i
#     book.unite = '本'
#     book.stock = i*100
#     book.sales = i*200
#     book.detail = 'python大法好,好啊真是好'*i
#     book.image = 'books/book00%d.jpg' % (i+1)
#     book.save()



    objects = BooksManager()

    class Meta:
        db_table = 's_books'
        verbose_name = '书籍信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

bookstore/books/views.py
from django.shortcuts import render, redirect
from books.models import Books
from books.enums import *
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
# from django.views.decorators.cache import cache_page
from django_redis import get_redis_connection

# Create your views here.

def index(request):
    """显示首页"""
    # 查询每个种类的３个新品信息和４个销量最好的商品信息
    python_new = Books.objects.get_books_by_type(PYTHON, 3, sort='new')
    python_hot = Books.objects.get_books_by_type(PYTHON, 4, sort='hot')
    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT, 3, sort='new')
    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT, 4, sort='hot')
    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS, 3, sort='new')
    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS, 4, sort='hot')
    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING, 3, sort='new')
    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING, 4, sort='hot')
    operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM, 3, sort='new')
    operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM, 4, sort='hot')
    database_new = Books.objects.get_books_by_type(DATABASE, 3, sort='new')
    database_hot = Books.objects.get_books_by_type(DATABASE, 4, sort='hot')
    # print(request.session['islogin'])
    # print(request.session['username'])
    # print(request.session['passport_id'])
    # TODO 定义模板上下文
    context = {'python_new': python_new,
               'python_hot': python_hot,
               'javascript_new': javascript_new,
               'javascript_hot': javascript_hot,
               'algorithms_new': algorithms_new,
               'algorithms_hot': algorithms_hot,
               'machinelearning_new': machinelearning_new,
               'machinelearning_hot': machinelearning_hot,
               'operatingsystem_new': operatingsystem_new,
               'operatingsystem_hot': operatingsystem_hot,
               'database_new': database_new,
               'database_hot': database_hot,

               }

    return render(request, 'books/index.html', context)


# 显示商品详情页
def detail(request, books_id):
    # 获取商品的详情信息
    books = Books.objects.get_books_by_id(books_id=books_id)

    if books is None:
        # 商品不存在,跳转到主页
        return redirect(reverse('book:book_index'))

    # 新品推荐
    books_li = Books.objects.get_books_by_type(type_id=books.type_id, limit=2, sort='new')

    # 用户登录之后,才记录浏览记录
    # 每个用户浏览记录对应redis中的一条信息 格式:'history_用户id:[10,9,2,3,4]
    # [9,10,2,3,4]
    if request.session.has_key('islogin'):
        # 用户已经登录, 记录浏览记录
        conn = get_redis_connection('default')
        key = 'history_%d' % request.session.get('passport_id')
        # 先从redis列表里一处books.id
        conn.lrem(key, 0, books.id)
        conn.lpush(key, books.id)
        # 保存用户最近浏览的5个商品
    # 定义上下文
    context = {'books': books, 'books_li': books_li}

    # 使用模板

    return render(request, 'books/detail.html', context)


# 商品种类 页码 排序方式
# /list (种类id)/(页码)/?sort=排序方式
def list(request, type_id, page):
    """商品列表页"""
    # 获取排序方式
    sort = request.GET.get('sort', 'default')

    # 判断type_id是否合法
    if int(type_id) not in BOOKS_TYPE.keys():
        return redirect(reverse('book:book_index'))

    # 根据商品种类id和排序方式查询数据
    books_li = Books.objects.get_books_by_type(type_id=type_id, sort=sort)

    # 分页
    paginator = Paginator(books_li, 20)

    # 获得分页以后的总页数
    num_pages = paginator.num_pages

    # 取第page页数据
    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)

    # 返回值是一个page类的实例对象
    books_li = paginator.page(page)

    # 进行页码控制
    # 1.总页数<5, 显示所有的页码
    # 2.当前页数是3,显示1-5页
    # 3.当前页是后3页,显示后5页
    # 4. 其他情况,显示当前页前2页,后2页,当前页
    if num_pages < 5:
        pages = range(1, num_pages + 1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages - 4, num_pages + 1)
    else:
        pages = range(page - 2, page + 3)

    # 新品推荐
    books_new = Books.objects.get_books_by_type(type_id=type_id, limit=2, sort='new')

    # 定义上下文
    type_title = BOOKS_TYPE[int(type_id)]
    context = {
        'books_li': books_li,
        'books_new': books_new,
        'type_id': type_id,
        'sort': sort,
        'type_title': type_title,
        'pages': pages,
    }

    # 使用模板
    return render(request, 'books/list.html', context)

bookstore/templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title  %}
尚硅谷书城-商品详情
{% endblock title%}
{% block topfiles %}
<script>
$(function () {
    update_total_price()
    // 计算总价
    function update_total_price() {
        // 获取商品的价格和数量
        books_price = $('.show_pirze').children('em').text()
        books_count = $('.num_show').val()
        // 计算商品的总价
        books_price = parseFloat(books_price)
        books_count = parseInt(books_count)
        total_price = books_price * books_count
        // 设置商品总价
        $('.total').children('em').text(total_price.toFixed(2) + '元')
    }

    // 商品增加
    $('.add').click(function () {
        // 获取商品的数量
        books_count = $('.num_show').val()
        // 加1
        books_count = parseInt(books_count) + 1
        // 重新设置值
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })

    // 商品减少
    $('.minus').click(function () {
        // 获取商品的数量
        books_count = $('.num_show').val()
        // 加1
        books_count = parseInt(books_count) - 1
        if (books_count == 0){
            books_count = 1
        }
        // 重新设置值
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })

    // 手动输入
    $('.num_show').blur(function () {
        // 获取商品的数量
        books_count = $(this).val()
        // 数据校验
        if (isNaN(books_count) || books_count.trim().length == 0 || parseInt(books_count) <= 0 ){
            books_count = 1
        }
        // 重新设置值
        $('.num_show').val(parseInt(books_count))
        // 计算总价
        update_total_price()
    })
})
</script>
{% endblock topfiles %}
<body>
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'book:book_index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img style="width: 350px; height: 350px" src="{% static books.image %}"></div>

		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
                <span class="show_pirze">￥<em> {{ books.price }} </em> </span>
				<span class="show_unit">单 位:{{ books.unit }}</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>100元</em></div>
			<div class="operate_btn">
				{% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
					{% for book in books_li %}
					<li>
						<a href="{% url 'book:book_detail' books_id=books.id %}"> <img src="{% static book.image %}"></a>
						<h4><a href="{% url 'book:book_detail' books_id=books.id %}">{{book.name}} </a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ books.detail | safe }}</dd>
				</dl>
			</div>

		</div>
	</div>

<div class="add_jump"></div>
{% endblock body %}
{% block bottomfiles %}
	<script>
    var $add_x = $('#add_cart').offset().top;
    var $add_y = $('#add_cart').offset().left;

    var $to_x = $('#show_count').offset().top;
    var $to_y = $('#show_count').offset().left;

    $('#add_cart').click(function(){
        // 获取商品的id和商品数量
        books_id = $(this).attr('books_id')
        books_count = $('.num_show').val()
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 发起请求，访问/cart/add/, 进行购物车数据的添加
        params = {
            'books_id': books_id, 
            'books_count': books_count,
            'csrfmiddlewaretoken': csrf
        }

        $.post('/cart/add/', params, function (data) {
            if (data.res == 5){
                // 添加成功
                $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                $(".add_jump").stop().animate({
                    'left': $to_y+7,
                    'top': $to_x+7},
                    "fast", function() {
                        $(".add_jump").fadeOut('fast',function(){
                            // 获取原有show_count的值
                            count = $('#show_count').html()
                            count = parseInt(count) + parseInt(books_count)
                            $('#show_count').html(count);
                        });
                });
            }
            else {
                // 添加失败
                alert(data.errmsg)
            }
        })
    })
</script>
{% endblock bottomfiles %}
</body>
</html>

bookstore/templates/books/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'book:book_index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="/static/images/adv02.jpg" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in python_new %}

                        <a href="{% url 'book:book_detail' books_id=book.id %}">{{ book.name }}</a>

                {% endfor %}
			</div>
			<a href="{% url 'book:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="book_list fl">
				{% for book in python_hot %}
                <li>
                    <h4><a href="{% url 'book:book_detail' books_id=book.id  %}">{{ book.name }}</a></h4>
                    <a href="{% url 'book:book_detail' books_id=book.id  %}"><img src="{% static book.image %}"></a>
                    <div class="prize">¥ {{ book.price }}</div>
                </li>
                {% endfor %}
				
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">Javascript高级编程</a>
				<a href="#">Javascript语言精粹</a>				
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">Javascript高级程序设计</a></h4>
					<a href="#"><img src="/static/images/book/book005.jpg"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript权威指南</a></h4>
					<a href="#"><img src="/static/images/book/book006.jpg"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript语言精粹</a></h4>
					<a href="#"><img src="/static/images/book/book007.jpg"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript DOM编程艺术</a></h4>
					<a href="#"><img src="/static/images/book/book008.jpg"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">算法导论</a>
				<a href="#">数据结构与算法分析</a>
				<a href="#">计算机程序设计艺术</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">数据结构与算法分析</a></h4>
					<a href="#"><img src="/static/images/book/book009.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">算法导论</a></h4>
					<a href="#"><img src="/static/images/book/book010.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">算法</a></h4>
					<a href="#"><img src="/static/images/book/book011.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">计算机程序设计艺术</a></h4>
					<a href="#"><img src="/static/images/book/book012.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">机器学习</a>
				<a href="#">统计学习方法</a>
				<a href="#">集体智慧编程</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner04.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">机器学习</a></h4>
					<a href="#"><img src="/static/images/book/book013.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">机器学习实战</a></h4>
					<a href="#"><img src="/static/images/book/book014.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">统计学习方法</a></h4>
					<a href="#"><img src="/static/images/book/book015.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">集体智慧编程</a></h4>
					<a href="#"><img src="/static/images/book/book016.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">UNIX环境高级编程</a>
				<a href="#">深入理解计算机系统</a>
				<a href="#">现代操作系统</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">现代操作系统</a></h4>
					<a href="#"><img src="/static/images/book/book017.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">深入理解计算机系统</a></h4>
					<a href="#"><img src="/static/images/book/book018.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">UNIX环境高级编程</a></h4>
					<a href="#"><img src="/static/images/book/book019.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">鸟哥的私房菜</a></h4>
					<a href="#"><img src="/static/images/book/book020.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">数据库系统概念</a>
				<a href="#">高性能MySQL</a>
				<a href="#">MySQL必知必会</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">数据库系统概念</a></h4>
					<a href="#"><img src="/static/images/book/book021.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">高性能MySQL</a></h4>
					<a href="#"><img src="/static/images/book/book022.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">Redis实战</a></h4>
					<a href="#"><img src="/static/images/book/book023.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">Redis设计与实现</a></h4>
					<a href="#"><img src="/static/images/book/book024.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>
{% endblock body %}

bookstore/templates/books/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title  %}
尚硅谷书城-商品列表
{% endblock title%}
<body>
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{type_title}}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
					{% for book in books_new %}
					<li>
						<a href="{% url 'book:book_detail' books_id=book.id%}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'book:book_detail' books_id=book.id %}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="/book/list/{{ type_id }}/1/" {% if sort == 'default' %} class="active"{% endif %}>默认</a>
				<a href="/book/list/{{ type_id }}/1/?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="/book/list/{{ type_id }}/1/?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="book_type_list clearfix">
				{% for books in books_li %}
					<li>
						<a href="{% url 'book:book_detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
						<div class="operate">
							<span class="prize">￥{{ books.price }}</span>
							<span class="unit">{{ books.unit}}</span>
							<a href="#" class="add_books" title=加入购物车></a>
						</div>
					</li>
				{% endfor %}
			</ul>
			<div class="pagenation">
				{% if books_li.has_previous %}
    				<a href="/book/list/{{ type_id }}/{{ books_li.previous_page_number }}/?sort={{ sort }}"><上一页</a>
				{% endif %}
				{% for pindex in pages %}
    				{% if pindex == books_li.number %}
        				<a href="/book/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}" class="active">{{ pindex }}</a>
    				{% else %}
        				<a href="/book/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}">{{ pindex }}</a>
    				{% endif %}
				{% endfor %}
					{% if books_li.has_next %}
    					<a href="/book/list/{{ type_id }}/{{ books_li.next_page_number }}/?sort={{ sort }}">下一页></a>
					{% endif %}
			</div>
		</div>
	</div>
{% endblock body %}
</body>
</html>