bookstore/books/urls.py
from django.conf.urls import  url
from books import views

urlpatterns = [
    url(r'^index/$', views.index, name='book_index'),
    url(r'^(?P<books_id>\d+)/$', views.detail, name='book_detail'),  # 配置详情页路由
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name = 'list'), # 列表页


]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import users

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^book/', include('books.urls', namespace='book')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
    url(r'^search/', include('haystack.urls')),
]

bookstore/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'), #添加购物车数据
    url(r'^count/$', views.cart_count, name='count'), # 获取用户购物车中的商品数量
    url(r'^show/$', views.cart_show, name='show'), # 显示用户的购物车页面
    url(r'^del/$', views.cart_del, name='delete'), # 购物车商品记录删除
    url(r'^update/$', views.cart_update, name='update'), # 更新购物车中的数据
    ]

bookstore/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_check/$', views.login_check, name='login_check'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^info_center/$', views.user, name='info_center'),
    url(r'^order/$', views.order, name='order'),
    url(r'^address/$', views.address, name='address'),

]

bookstore/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页顶部标题块 #}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% block cart_count %}
    <script>
        $.get('/cart/count/', function(data){
            //{'res':商品的总数}
            $('#show_count').html(data.res)
        })
    </script>
    {% endblock cart_count %}
    <script>
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $('#add_cart').click(function(){
            //获取商品的id和商品的数量
            books_id = $(this).attr('books_id');
            books_count = $('.num_show').val();
            csrf = $("input[name='csrfmiddlewaretoken']").val();
            //发起请求, 访问/cart/add/,进行购物车数据的添加
            params = {
                'books_id':books_id,
                'books_count': books_count,
                'csrfmiddlewaretoken':csrf,
            };

            $.post('/cart/add/', params, function(data){
                if (data.res === 5){
                    //添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
                    $(".add_jump").stop().animate({
                        'left':$to_y+7,
                        'top':$to_x+7},
                        "fast",function(){
                            $(".add_jump").fadeOut('fast',function(){
                                // 获取原有的show_count的值
                                count = $('#show_count').html();
                                count = parseInt(count) + parseInt(books_count);
                                $('#show_count').html(count);
                            });
                        });
                }
                else{
                    //添加失败
                    alert(data.errmsg)
                }
            })
        })
    </script>
    {# 网页顶部引入文件块 #}
    {% block topfiles %}
    {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到尚硅谷书店</div>
            <div class="fr">
                {% if request.session.islogin %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                </div>
                {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:info_center' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="#">我的订单</a>
                </div>
            </div>
        </div>      
    </div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'book:book_index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
        <div class="search_con fl">
            <form method='get' action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
{#                <input type="text" name="q">#}
{#                <input type="submit" value="查询">#}
            </form>
{#            <input type="text" class="input_text fl" name="" placeholder="搜索商品">#}
{#            <input type="button" class="input_btn fr" name="" value="搜索">#}
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
            <div class="book_count fl" id="show_count">0</div>
        </div>
    </div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}
{% endblock body %}

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888    京ICP备*******8号</p>
    </div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>